name: hsl_colorpicker
description: A beatyfull HSL Color Picker for Flutter
version: 1.0.1
author: CheckHelzio
homepage: https://github.com/CheckHelzio/hsl_color_picker

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter